import type { Metadata } from 'next'
import { Schibsted_Grotesk } from 'next/font/google'

import './globals.css'
import { Providers } from './providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const schibsted_Grotesk = Schibsted_Grotesk({
  weight: '400',
  subsets: ['latin'],
  display: 'swap'
})

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <Providers>
      <html lang="en" className={schibsted_Grotesk.className}>
        <body>{children}</body>
      </html>
    </Providers>
  )
}
